<?php

/**
 * @file
 * Hooks and callbacks for this module.
 */

/**
 * Implements hook_menu().
 */
function dgi_sample_menu() {
  $items = array();
  $items['admin/islandora/sample'] = array(
    'title' => 'Sample contents',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('dgi_sample_admin'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
* Implements hook_css_alter().
*/
function dgi_sample_css_alter(&$css) {
  // override Seven's css Admin stylesheet.
  if (isset($css['themes/seven/style.css'])) {
    $css['themes/seven/style.css']['data'] = drupal_get_path('module', 'dgi_sample') . '/css/seven_style.css';
  }
}

/**
 * Implements hook_islandora_required_objects().
 */
function dgi_sample_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'dgi_sample');

  // Image Objects.
  $img_objects = array();

  // Sample Collection Object.
  $collection_object = $connection->repository->constructObject("islandora:sample_collection");
  $collection_object->owner = 'admin';
  $collection_object->label = 'Sample';
  $collection_object->models = 'islandora:collectionCModel';
  $collection_object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');

  // COLLECTION_POLICY.
  $datastream = $collection_object->constructDatastream('COLLECTION_POLICY');
  $datastream->label = 'COLLECTION_POLICY';
  $datastream->mimetype = 'image/jpeg';
  $datastream->setContentFromFile("$module_path/objects/collections/sample/COLLECTION_POLICY.xml", FALSE);
  $collection_object->ingestDatastream($datastream);

  $objects = file_scan_directory("$module_path/objects/sample_photos", "/.+/", array('recurse' => FALSE));
  foreach ($objects as $object) {
    $filename = preg_replace('/[[:punct:]]/', '', $object->filename);
    $filename = str_replace(' ', '_', $filename);
    $img_objects[$object->filename] = $connection->repository->constructObject("islandora:sample_$filename");
    $img_objects[$object->filename]->owner = 'admin';
    $img_objects[$object->filename]->label = $object->filename;
    $img_objects[$object->filename]->models = 'islandora:sp_basic_image';
    $img_objects[$object->filename]->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:sample_collection');

    // DC record.
    $datastream = $img_objects[$object->filename]->constructDatastream('DC');
    $datastream->label = 'DC Record';
    $datastream->mimetype = 'text/xml';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/DC.xml", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // MODS record.
    $datastream = $img_objects[$object->filename]->constructDatastream('MODS');
    $datastream->label = 'MODS Record';
    $datastream->mimetype = 'text/xml';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/MODS.xml", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // RELS-EXT.
    $datastream = $img_objects[$object->filename]->constructDatastream('RELS-EXT');
    $datastream->label = 'Fedora Object to Object Relationship Metadata.';
    $datastream->mimetype = 'application/rdf+xml';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/RELS-EXT.rdf", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // OBJ.
    $datastream = $img_objects[$object->filename]->constructDatastream('OBJ');
    $datastream->label = $object->filename;
    $datastream->mimetype = 'image/jpeg';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/OBJ.jpg", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // MEDIUM_SIZE.
    $datastream = $img_objects[$object->filename]->constructDatastream('MEDIUM_SIZE');
    $datastream->label = 'MEDIUM_SIZE';
    $datastream->mimetype = 'image/jpeg';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/MEDIUM_SIZE.jpg", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // TN.
    $datastream = $img_objects[$object->filename]->constructDatastream('TN');
    $datastream->label = 'TN';
    $datastream->mimetype = 'image/jpeg';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/TN.jpg", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);

    // TECHMD.
    $datastream = $img_objects[$object->filename]->constructDatastream('TECHMD');
    $datastream->label = 'TECHMD';
    $datastream->mimetype = 'text/xml';
    $datastream->setContentFromFile("$module_path/objects/sample_photos/$object->filename/TECHMD.xml", FALSE);
    $img_objects[$object->filename]->ingestDatastream($datastream);
  }
  $object_array = array_merge($img_objects, array($collection_object));
  return array(
    'dgi_sample' => array(
      'title' => 'DGI Sample content',
      'objects' => $object_array,
    ),
  );
}

/**
 * Set the accordion pid list variable.
 */
function dgi_sample_accordion_pid_list() {
  $value = dgi_sample_get_pid_list();
  variable_set('accordion_pid_list', $value);
}

/**
 * Get the pid list for sample objects.
 * 
 * @return string
 *   The pid list.
 */
function dgi_sample_get_pid_list() {
  $module_path = drupal_get_path('module', 'dgi_sample');
  $objects = file_scan_directory("$module_path/objects/sample_photos", "/.+/", array('recurse' => FALSE));
  $i = 0;
  $value = '';
  foreach ($objects as $object) {
    $filename = preg_replace('/[[:punct:]]/', '', $object->filename);
    $filename = str_replace(' ', '_', $filename);
    if (islandora_object_load("islandora:sample_$filename") && $i < 4) {
      $value .= "islandora:sample_$filename,";
      $i++;
    }
  }
  return $value;
}
